# Generated by Django 5.2 on 2025-05-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Networkar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('governorate', models.CharField(max_length=100, verbose_name='Governorate')),
                ('area', models.CharField(max_length=100, null=True, verbose_name='Area')),
                ('type', models.CharField(max_length=100, verbose_name='Type')),
                ('speciality', models.CharField(max_length=255, verbose_name='Speciality')),
                ('provider', models.CharField(max_length=255, verbose_name='Provider')),
                ('discount', models.CharField(blank=True, max_length=50, null=True, verbose_name='Discount')),
                ('address', models.TextField(null=True, verbose_name='Address')),
                ('phone', models.CharField(max_length=100, verbose_name='Phone')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
        ),
    ]
