# Generated by Django 5.2 on 2025-05-03 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('governorate', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('type', models.CharField(max_length=100, verbose_name='Type')),
                ('speciality', models.CharField(max_length=255, verbose_name='Speciality')),
                ('provider', models.CharField(max_length=255, verbose_name='Provider')),
                ('discount', models.CharField(max_length=50, verbose_name='Discount')),
                ('address', models.TextField(verbose_name='Address')),
                ('phone', models.CharField(max_length=100, verbose_name='Phone')),
                ('website', models.URLField(verbose_name='Website')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('notes', models.TextField(verbose_name='Notes')),
            ],
        ),
    ]
