# Generated by Django 5.2 on 2025-05-03 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='discount',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='network',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='network',
            name='governorate',
            field=models.CharField(max_length=100, verbose_name='Governorate'),
        ),
        migrations.AlterField(
            model_name='network',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='network',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
    ]
