# Generated by Django 5.2 on 2025-05-03 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_network_discount_alter_network_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='city',
        ),
        migrations.AddField(
            model_name='network',
            name='area',
            field=models.CharField(max_length=100, null=True, verbose_name='Area'),
        ),
    ]
