# Generated by Django 5.2 on 2025-05-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_networkar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkar',
            name='address',
            field=models.TextField(null=True, verbose_name='Address'),
        ),
    ]
