# Generated by Django 5.2 on 2025-05-03 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_networkar_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Networkar',
        ),
    ]
